version: "3.8"

services:
    php:
        image: '${PHP_IMAGE:-changeme/changeme-php:staging}'
        restart: unless-stopped
        env_file:
            - .env.prod
        volumes:
            - ./:/var/www/html
            - app-data:/var/www/html/var
            - app-uploads:/var/www/html/public/uploads

    nginx:
        image: '${NGINX_IMAGE:-changeme/changeme-nginx:staging}'
        restart: unless-stopped
        volumes:
            - ./public:/var/www/html/public:ro
            - ./wp:/var/www/html/wp:ro
            - app-uploads:/var/www/html/public/uploads:ro
        depends_on:
            - php
            - traefik
        networks:
            - default
            - traefik
        labels:
            - traefik.enable=true
            - traefik.http.routers.${APP_NAME:-sword}.rule=Host(`${PRODUCTION_DOMAIN:-staging.example.com}`)
            - traefik.http.routers.${APP_NAME:-sword}.tls=true
            - traefik.http.routers.${APP_NAME:-sword}.entrypoints=websecure
            - traefik.http.services.${APP_NAME:-sword}.loadbalancer.server.port=80

    mysql:
        image: mysql:8.0.37
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
            MYSQL_DATABASE: ${WORDPRESS_DB_NAME:-sword_app}
            MYSQL_USER: ${WORDPRESS_DB_USER:-user}
            MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD:-user}
        volumes:
            - mysql_data:/var/lib/mysql

    traefik:
        image: traefik:2.11
        ports:
            - '443:443'
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        networks:
            - traefik
        command:
            - --providers.docker
            - --providers.docker.exposedbydefault=false
            - --providers.docker.network=${PROJECT_DIR:-sword}_traefik
            - --entrypoints.web.address=:80
            - --entrypoints.web.http.redirections.entryPoint.to=websecure
            - --entrypoints.web.http.redirections.entryPoint.scheme=https
            - --entrypoints.websecure.address=:443

volumes:
    mysql_data:
    app-data:
    app-uploads:

networks:
    traefik:
